version: "3.7"
services:
  web:
    image: guyraws/slack-clone_node:v1
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    depends_on:
      - db
    # command: ["bash", "./wait-for-it.sh", "db"]
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:docker@db:5432/postgres
      
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
    volumes:
      - ~/docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
