version: "3.7"
services:
  web:
    image: slack-clone/node:v1
    depends_on:
      - 'db'
      command: ["./wait-for-postgres.sh", "db", "python", "app.py"]
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://username:pgpassword@db:5432/postgres
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
    volumes:
      - ~/docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
